server {
    listen 80;
    server_name _;

    #
    # Optional:
    # Redirect root to the default locale.
    #
    location = / {
        return 302 /en-US/;
    }

    #
    # Everything else goes to Angular
    #
    location / {
        proxy_pass http://main-client:9001;

        proxy_http_version 1.1;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;
    }
}